adminsite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('control/', include('control.urls')),
    path('admin/', admin.site.urls),
]

control/urls.py
from django.urls import path

from . import views
from django.contrib.auth import views as auth_views

app_name = 'control'
urlpatterns = [
    path('', views.index, name='index'),

    # log in / log out
    path('login/', auth_views.LoginView.as_view(template_name='control/login.html'), name='login'),
    path('logout/', views.logout, name='logout'),

    # Gait
    path('newGait/<int:person_id>/', views.newGait, name='newGait'),

    # Person
    path('persons/', views.persons, name='persons'),
    path('person/<int:person_id>/', views.person, name='person'),

    # Door
    path('doors/', views.doors, name='doors'),
    path('door/<int:door_id>', views.door, name='door'),
    path('door2/<int:door_id>/<int:x>/<int:y>/', views.door2, name='door2'),

    # API
    path('doorquery/<int:door_id>/', views.doorQuery, name='doorQuery'),
]

control/models.py
from django.db import models

# Create your models here.
class Gait(models.Model):
    data = models.CharField(max_length=200)

class Fingerprint(models.Model):
    data = models.CharField(max_length=200)

class Person(models.Model):
    name = models.CharField(max_length=200)
    LEVEL1 = '1'
    LEVEL2 = '2'
    LEVEL3 = '3'
    PRIVILEGE = (
        (LEVEL1, '低'),
        (LEVEL2, '中'),
        (LEVEL3, '高'),
    )
    privilege = models.CharField(
        max_length=1,
        choices=PRIVILEGE,
        default=LEVEL1,
    )
    gait = models.ForeignKey(Gait, on_delete=models.SET_NULL, null=True, blank=True)
    fingerprint = models.ForeignKey(Fingerprint, on_delete=models.SET_NULL, null=True, blank=True)


class Door(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    LEVEL1 = '1'
    LEVEL2 = '2'
    LEVEL3 = '3'
    LEVEL = (
        (LEVEL1, '低'),
        (LEVEL2, '中'),
        (LEVEL3, '高'),
    )
    level = models.CharField(
        max_length=1,
        choices=LEVEL,
        default=LEVEL3,
    )

class DoorOpen(models.Model):
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    door = models.ForeignKey(Door, on_delete=models.CASCADE)
    dt = models.DateTimeField('time')
    GAIT = '0'
    FINGERPRINT = '1'
    METHOD = (
        (GAIT, '步态识别'),
        (FINGERPRINT, '指纹识别'),
    )
    method = models.CharField(
        max_length=1,
        choices=METHOD,
        default=GAIT,
    )

control/views.py
import datetime

from django.contrib.auth import views as auth_views
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q, Count
from django.contrib.auth.decorators import login_required

import numpy as np
from sklearn import neighbors

from .models import Person, Door

def index(request):
    return render(request, 'control/index.html')

def logout(request):
    return auth_views.logout_then_login(request,login_url='/control/login')

# --------------------
# Gait
# --------------------
def newGait(request, person_id):
    if request.user.is_authenticated:
        person = get_object_or_404(Person, pk=person_id)
        return render(request, 'control/newGait.html', {'person': person})
    else:
        return render(request, 'control/login.html', {'next': request })

# --------------------
# Person
# --------------------
@login_required(login_url='/control/login/')
def persons(request):
    persons = Person.objects.all()
    return render(request, 'control/persons.html', {'persons': persons })

@login_required(login_url='/control/login/')
def person(request, person_id):
    person = get_object_or_404(Person, pk=person_id)
    table = dict(
        zip(
            [timezone.now() - datetime.timedelta(hours=i * 4 + 150) for i in range(1, 25)]
            ,
            [[person.dooropen_set.filter(Q(dt__gte=timezone.now() - datetime.timedelta(hours=i * 4 + 150)) & Q(dt__lt=timezone.now() - datetime.timedelta(hours=(i - 1) * 4 + 150)) & Q(door__level=str(j))).count() for j in range(1, 4)] for i in range(1, 25)]
        )
    )
    doors = person.dooropen_set.filter(dt__gte=timezone.now() - datetime.timedelta(days=3 + 6)).values('door__id', 'door__name').annotate(num=Count('door__id')).order_by('-num')
    logs = person.dooropen_set.all().order_by('-dt')[:10]
    methods = list(person.dooropen_set.filter(dt__gte=timezone.now() - datetime.timedelta(days=3 + 6)).values('method').annotate(num=Count('method')))
    if len(methods) == 1:
        if methods[0]['method'] == '0':
            methods.append({'method': '1', 'num': 0})
        else:
            methods.insert(0, {'method': '0', 'num': 0})

    return render(request, 'control/person.html', {'person':person, 'table': table, 'doors':doors, 'logs': logs, 'methods': methods})

# --------------------
# Door
# --------------------
@login_required(login_url='/control/login/')
def doors(request):
    doors = Door.objects.all()
    return render(request, 'control/doors.html', {'doors': doors})

@login_required(login_url='/control/login/')
def door(request, door_id):
    door = get_object_or_404(Door, pk=door_id)
    table = dict(
        zip(
            [timezone.now() - datetime.timedelta(hours=i*4+144) for i in range(1, 25)]
        ,
            [ [door.dooropen_set.filter(Q(dt__gte=timezone.now() - datetime.timedelta(hours=i*4+144)) & Q(dt__lt=timezone.now() - datetime.timedelta(hours=(i-1)*4+144)) & Q(person__privilege=str(j))).count() for j in range(1,4)] for i in range(1, 25)]
        )
    )
    persons = door.dooropen_set.filter(dt__gte=timezone.now()-datetime.timedelta(days=3+6)).values('person__id', 'person__name').annotate(num=Count('person__id')).order_by('-num')[:5]
    logs = door.dooropen_set.all().order_by('-dt')[:10]
    methods = list(door.dooropen_set.filter(dt__gte=timezone.now()-datetime.timedelta(days=3+6)).values('method').annotate(num=Count('method')))
    if len(methods) == 1:
        if methods[0]['method'] == '0':
            methods.append({'method': '1', 'num': 0})
        else:
            methods.insert(0, {'method': '0', 'num': 0})

    return render(request, 'control/door.html', {'door': door, 'table': table, 'persons': persons, 'logs': logs, 'methods':methods})

@login_required(login_url='/control/login/')
def door2(request, door_id, x, y):
    door = get_object_or_404(Door, pk=door_id)
    table = dict(
        zip(
            [timezone.now() - datetime.timedelta(hours=i*x) for i in range(1, y+1)]
        ,
            [ [door.dooropen_set.filter(Q(dt__gte=timezone.now() - datetime.timedelta(hours=i*x)) & Q(dt__lt=timezone.now() - datetime.timedelta(hours=(i-1)*x)) & Q(person__privilege=str(j))).count() for j in range(1,4)] for i in range(1, y+1)]
        )
    )
    persons = door.dooropen_set.filter(dt__gte=timezone.now() - datetime.timedelta(days=3)).values('person__id','person__name').annotate(num=Count('person__id')).order_by('-num')[:5]
    logs = door.dooropen_set.all().order_by('-dt')[:10]
    methods = list(
        door.dooropen_set.filter(dt__gte=timezone.now() - datetime.timedelta(days=3)).values('method').annotate(
            num=Count('method')))
    if len(methods) == 1:
        if methods[0]['method'] == '0':
            methods.append({'method': '1', 'num': 0})
        else:
            methods.insert(0, {'method': '0', 'num': 0})
    return render(request, 'control/door.html', {'door': door, 'table': table, 'persons': persons, 'logs': logs, 'methods': methods})

# --------------------
# API
# --------------------
@csrf_exempt
def doorQuery(request, door_id):
    door = get_object_or_404(Door, pk=door_id)
    if request.method == 'POST':
        st1 = request.POST['st1']
        sts = st1.split(' ')
        sts.pop()
        f = open("data.txt")
        data = np.loadtxt(f)

        X = data[:, :66]
        y = data[:, 66]

        testX = [[float(i) for i in sts]]

        n_neighbors = 3
        h = .02  # step size in the mesh

        weights = 'uniform'
        # we create an instance of Neighbours Classifier and fit the data.
        clf = neighbors.KNeighborsClassifier(n_neighbors, weights=weights)
        clf.fit(X, y)

        return HttpResponse(str(int(clf.predict(testX)[0])))
    else:
        return HttpResponse(str(door.name)+ ' (it\'s not a POST)')

control/templates/control/index.html
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="refresh" content="0;url=/static/pages/index.html">
<title>SB Admin 2</title>
<script language="javascript">
    window.location.href = "/static/pages/index.html"
</script>
</head>
<body>
Go to <a href="/static/pages/index.html">/static/pages/index.html</a>
</body>
</html>

control/templates/control/login.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Bootstrap Admin Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="/static/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/dist/css/sb-admin-2.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/static/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="login-panel panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">登录</h3>
                    </div>
                    <div class="panel-body">
                                {% block content %}

                                {% if form.errors %}
                                <div class="alert alert-danger">
                                    <p>帐户名或密码错误</p>
                                </div>
                                {% endif %}

                                {% if next %}
                                {% if user.is_authenticated %}
                                <div class="alert alert-info">
                                    <p>您的账户没有访问当前页面的权限</p>
                                </div>
                                {% else %}
                                <div class="alert alert-info">
                                    <p>登录以显示此页面</p>
                                </div>
                                {% endif %}
                                {% endif %}

                                <form method="post" action="{% url 'control:login' %}">
                                    <fieldset>
                                    {% csrf_token %}
                                    <table>
                                        <div class="form-group">
                                            <input id="id_username" name="username" placeholder="用户名" type="text" class="form-control">
                                        </div>
                                        <div class="form-group">
                                            <input id="id_password" name="password" placeholder="密码" type="password" class="form-control">
                                        </div>
                                    </table>
                                    <div class="form-group">
                                        <input type="submit" class="btn btn-lg btn-success btn-block" value="登录"/>
                                    </div>
                                    <input type="hidden" name="next" value="{{ next }}"/>
                                    </fieldset>
                                </form>

                                {# Assumes you setup the password_reset view in your URLconf #}

                                {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- jQuery -->
    <script src="/static/vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Metis Menu Plugin JavaScript -->
    <script src="/static/vendor/metisMenu/metisMenu.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="/static/dist/js/sb-admin-2.js"></script>

</body>

</html>